7z x "%appdata%\.minecraft\Temp\assets.7z.001" "-o%appdata%\.minecraft" "-aoa"
7z x "%appdata%\.minecraft\Temp\libraries.7z.001" "-o%appdata%\.minecraft" "-aoa"
7z x "%appdata%\.minecraft\Temp\mods.7z.001" "-o%appdata%\.minecraft" "-aoa"
7z x "%appdata%\.minecraft\Temp\shaderpacks.7z" "-o%appdata%\.minecraft" "-aoa"
7z x "%appdata%\.minecraft\Temp\versions.7z" "-o%appdata%\.minecraft" "-aoa"